liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%env(CDN_BASE_DIR)%'
                cache_prefix: "media/cache/thumbs"
    loaders:
        default:
            filesystem:
                data_root:
                    - '%env(CDN_BASE_DIR)%'